Scaffold blog template
interglobalvision/shop-apt25-com-mx pull request #9
Opened 2017-10-19 22:43 UTC by mixcas

2017-10-20 13:11 UTC, varffs commented
Does in progress label mean do not review and merge? (I'm not going to just in case)

2017-10-20 13:12 UTC, mixcas commented
idk… @mikeyrayvon ?

2017-10-20 16:51 UTC, mikeyrayvon commented
i did not add that label...

2017-10-20 18:46 UTC, mixcas commented
plz close

2017-10-20 20:32 UTC, mikeyrayvon requested changes

2017-10-20 20:32 UTC, mikeyrayvon commented on src/css/grid.styl
> +    .container-large
can we call this `.container-full`

2017-10-20 20:32 UTC, mikeyrayvon commented on src/css/grid.styl
> +    .container-medium
and this `.container-mid` in keeping with grid naming conventions

2017-10-20 20:32 UTC, mikeyrayvon commented on src/css/grid.styl
> +
actually scratch that. use grid items & offsets within the normal container rather than various container sizes

2017-10-20 20:32 UTC, mikeyrayvon commented on templates/blog.liquid
> +                {% if article.image %}<img class="margin-bottom-tiny" src="{{ article | img_url: 'master' }}">{% endif %}
use a srcset here. see `templates/collection.liquid line 52`

2017-10-20 20:32 UTC, mikeyrayvon commented on templates/blog.liquid
> +                {% if article.image %}<img class="margin-bottom-tiny" src="{{ article | img_url: 'original' }}">{% endif %}
srcset

2017-10-20 20:32 UTC, mikeyrayvon commented on templates/blog.liquid
> +                <img class="logo" src="{{ 'arrow-right.svg' | asset_url }}">
`class="logo"` 👎

2017-10-20 20:32 UTC, mikeyrayvon commented on templates/blog.liquid
> +              <p class="margin-bottom-tiny">{{ article.excerpt }}{{ dash }}<span class="fa fa-eye"></span></p>
bring these icons in as svgs from `/assets`
i'll find them for u

2017-10-24 15:04 UTC, varffs commented
Whats up with this? @mikeyrayvon you requested changes and made them now it needs review? If so please (approve your own changes??? and) assign someone else to the PR

2017-10-24 19:21 UTC, mixcas commented
All code is fine.

I fixed the srcset. `sizes` was wrong also since in this case sizes grow in a linear way with the viewport width there's no need to specify `sizes`.

I'm gonna wait @mikeyrayvon to talk about this.

2017-10-25 20:07 UTC, mikeyrayvon approved these changes

2017-10-25 20:09 UTC, mikeyrayvon commented on templates/blog.liquid
> +                         {% if image.width >= 700 %},{{ image.src | img_url: '700x292', crop: 'center' }} 700w{% endif %}
maybe this one unnecessary cause 700 width probably weighs around the same as 744?

2017-10-26 17:42 UTC, merged